name: Deploy with Docker Compose

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SECRET_KYE }}  # SECRET_KYE로 수정

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no -p 40022 aceit@182.217.20.249 << 'EOF'
          cd /home/test1  # 서버의 프로젝트 경로로 이동
          docker-compose down  # 기존 컨테이너 중지
          docker-compose up -d --build  # 컨테이너 빌드 및 실행
        EOF
      env:
        DOCKER_HOST: "ssh://aceit@182.217.20.249"
